2018-05-03 20:07:08,959 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app.py:71]
2018-05-03 21:51:19,423 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app.py:75]
2018-05-04 23:40:51,022 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-04 23:41:53,167 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-04 23:42:13,738 ERROR: Exception on /favicon.ico [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-04 23:42:13,891 ERROR: Exception on /favicon.ico [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-04 23:48:55,271 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-04 23:50:27,542 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-04 23:50:45,852 ERROR: Exception on /favicon.ico [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
2018-05-05 11:12:53,960 INFO: blogapp startup [in /home/jaume/Flask/blogapp/app/__init__.py:61]
2018-05-05 11:13:18,748 ERROR: Exception on /favicon.ico [GET] [in /home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/app.py", line 1471, in handle_http_exception
    return handler(e)
  File "/home/jaume/Flask/blogapp/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jaume/Flask/blogapp/app/templates/404.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jaume/Flask/blogapp/app/templates/layout.html", line 45, in top-level template code
    {% include 'includes/_header.html' %}
  File "/home/jaume/Flask/blogapp/app/templates/includes/_header.html", line 1, in top-level template code
    {% if header.needed == True %}
  File "/home/jaume/Flask/blogapp/BlogAppVirtualEnvironment/local/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'header' is undefined
